apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mesos-service-account-rolebinding
  namespace: mesos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mesos-service-account-role
subjects:
- namespace: mesos
  kind: ServiceAccount
  name: mesos-service-account